version: '3' 
services:
  sgx_dev:
    build: .
    container_name: sgx
    volumes:
     - ./EnclaveProtocol:/home/syssec/EnclaveProtocol
    tty: true
    working_dir: /home/syssec/EnclaveProtocol/
    command: ./run.sh
